export const studioEditorCopy = {
  pl: { queued: 'W kolejce…', planning: 'Analizuję zadanie i planuję…', checking: 'Sprawdzam pliki projektu…', saving: 'Zapisuję nową wersję…', needsInput: 'Czekam na Twoją odpowiedź', execution: 'Przebieg pracy', plan: 'Plan wykonania', read: 'Odczyt', write: 'Zmiana pliku', search: 'Wyszukiwanie', execute: 'Wykonanie', delegate: 'Zadanie agenta', harnessBlocked: 'Zadanie zatrzymało się przed ukończeniem. Dotychczasowa wersja pozostaje dostępna.', harnessUnavailable: 'Nie udało się uruchomić silnika projektowego. Spróbuj ponownie.', exportHistory: 'Zapisane eksporty', noExports: 'Wyeksportowane pliki pojawią się tutaj.', downloadAgain: 'Pobierz ponownie', exportSaveFailed: 'Plik został pobrany, ale nie udało się zapisać jego kopii w projekcie.', expired: 'Sesja wygasła. Otwórz Studio ponownie z Semurai. Niezapisany projekt możesz pobrać jako HTML.', duplicateSlide: 'Duplikuj slajd', removeSlide: 'Usuń slajd', moveUp: 'Przesuń wcześniej', moveDown: 'Przesuń dalej', back: 'Wróć do czatu', saved: 'Zapisano', unsaved: 'Niezapisane zmiany', save: 'Zapisz', preview: 'Podgląd', source: 'Źródło', edit: 'Edytuj',
    desktop: 'Komputer', tablet: 'Tablet', mobile: 'Telefon', undo: 'Cofnij', redo: 'Ponów', history: 'Historia', export: 'Eksport',
    chat: 'Czat projektu', ask: 'Co chcesz zmienić w projekcie?', send: 'Wyślij', working: 'Wprowadzam zmiany…', completed: 'Nowa wersja gotowa',
    failed: 'Nie udało się ukończyć zmiany', cancelled: 'Anulowano', cancelling: 'Anuluję…', generatingImage: 'Generuję zdjęcie…', cancel: 'Anuluj', retry: 'Spróbuj ponownie', restore: 'Przywróć',
    empty: 'Twój projekt czeka na pierwszy pomysł.', emptyHelp: 'Opisz, co chcesz stworzyć. Wynik pojawi się tutaj.',
    error: 'Nie udało się wykonać tej operacji. Spróbuj ponownie.', conflict: 'Zapisano nowszą wersję. Twoje lokalne zmiany pozostają w edytorze.',
    notes: 'Notatki prelegenta', present: 'Prezentuj', layers: 'Elementy', inspect: 'Style i właściwości', downloadHtml: 'HTML + CSS',
    downloadPptx: 'PowerPoint', print: 'Drukuj / PDF', version: 'Wersja', loading: 'Otwieram projekt…', close: 'Zamknij',
    allChanges: 'Każda ukończona zmiana AI zapisuje nową wersję.', localImage: 'Obraz', zoom: 'Powiększenie', newProject: 'Semurai Creative',
    files: 'Pliki projektu', html: 'index.html', css: 'Style CSS', fullscreen: 'Pełny ekran', savedSource: 'Źródło projektu',
    backToSemurai: 'Wróć do Semurai', closeSession: 'Zamknij sesję', more: 'Więcej opcji', collapsePanel: 'Zwiń panel', expandPanel: 'Pokaż panel',
    modeChat: 'Czat', modeEdit: 'Edycja', tools: 'Narzędzia', toolSelect: 'Zaznacz', toolSelectHint: 'Podgląd projektu i czat AI', toolComment: 'Komentarz', toolCommentHint: 'Komentuj elementy projektu',
    toolEdit: 'Edycja', toolEditHint: 'Edytuj elementy ręcznie', openComments: 'Otwarte komentarze', view: 'Widok', devices: 'Urządzenie',
    zoomIn: 'Powiększ', zoomOut: 'Pomniejsz', zoomFit: 'Dopasuj do szerokości', presentStart: 'Od początku', presentCurrent: 'Od bieżącego slajdu', presenterView: 'Widok prezentera',
    sheet: 'Arkusz', currentVersion: 'Bieżąca', exportMenu: 'Opcje eksportu' },
  en: { queued: 'Queued…', planning: 'Reviewing the request and planning…', checking: 'Checking project files…', saving: 'Saving the new version…', needsInput: 'Waiting for your answer', execution: 'Execution record', plan: 'Execution plan', read: 'Read', write: 'Update file', search: 'Search', execute: 'Execute', delegate: 'Agent task', harnessBlocked: 'The task stopped before completion. Your previous version remains available.', harnessUnavailable: 'The design engine could not start. Please retry.', exportHistory: 'Saved exports', noExports: 'Your exported files will appear here.', downloadAgain: 'Download again', exportSaveFailed: 'Your file was downloaded, but a copy could not be saved to this project.', expired: 'Session expired. Reopen Studio from Semurai. You can download unsaved work as HTML.', duplicateSlide: 'Duplicate slide', removeSlide: 'Delete slide', moveUp: 'Move earlier', moveDown: 'Move later', back: 'Back to chat', saved: 'Saved', unsaved: 'Unsaved changes', save: 'Save', preview: 'Preview', source: 'Source', edit: 'Edit',
    desktop: 'Desktop', tablet: 'Tablet', mobile: 'Mobile', undo: 'Undo', redo: 'Redo', history: 'History', export: 'Export',
    chat: 'Project chat', ask: 'What would you like to change?', send: 'Send', working: 'Applying changes…', completed: 'New version ready',
    failed: 'The change could not be completed', cancelled: 'Cancelled', cancelling: 'Cancelling…', generatingImage: 'Generating image…', cancel: 'Cancel', retry: 'Retry', restore: 'Restore',
    empty: 'Your project starts with an idea.', emptyHelp: 'Describe what you want to create. Your result will appear here.',
    error: 'This action could not be completed. Please try again.', conflict: 'A newer version was saved. Your local changes remain in the editor.',
    notes: 'Speaker notes', present: 'Present', layers: 'Elements', inspect: 'Styles and properties', downloadHtml: 'HTML + CSS',
    downloadPptx: 'PowerPoint', print: 'Print / PDF', version: 'Version', loading: 'Opening project…', close: 'Close',
    allChanges: 'Each completed AI change saves a new version.', localImage: 'Image', zoom: 'Zoom', newProject: 'Semurai Creative',
    files: 'Project files', html: 'index.html', css: 'CSS styles', fullscreen: 'Full screen', savedSource: 'Project source',
    backToSemurai: 'Back to Semurai', closeSession: 'Close session', more: 'More options', collapsePanel: 'Collapse panel', expandPanel: 'Show panel',
    modeChat: 'Chat', modeEdit: 'Edit', tools: 'Tools', toolSelect: 'Select', toolSelectHint: 'Project preview and AI chat', toolComment: 'Comment', toolCommentHint: 'Comment on project elements',
    toolEdit: 'Edit', toolEditHint: 'Edit elements by hand', openComments: 'Open comments', view: 'View', devices: 'Device',
    zoomIn: 'Zoom in', zoomOut: 'Zoom out', zoomFit: 'Fit to width', presentStart: 'From the beginning', presentCurrent: 'From current slide', presenterView: 'Presenter view',
    sheet: 'Sheet', currentVersion: 'Current', exportMenu: 'Export options' },
  de: { queued: 'In der Warteschlange…', planning: 'Anfrage analysieren und planen…', checking: 'Projektdateien prüfen…', saving: 'Neue Version speichern…', needsInput: 'Warte auf deine Antwort', execution: 'Arbeitsverlauf', plan: 'Ausführungsplan', read: 'Lesen', write: 'Datei ändern', search: 'Suchen', execute: 'Ausführen', delegate: 'Agent-Aufgabe', harnessBlocked: 'Die Aufgabe wurde vor dem Abschluss gestoppt. Deine vorherige Version bleibt verfügbar.', harnessUnavailable: 'Die Design-Engine konnte nicht gestartet werden. Bitte erneut versuchen.', exportHistory: 'Gespeicherte Exporte', noExports: 'Exportierte Dateien erscheinen hier.', downloadAgain: 'Erneut herunterladen', exportSaveFailed: 'Die Datei wurde heruntergeladen, aber eine Kopie konnte nicht im Projekt gespeichert werden.', expired: 'Sitzung abgelaufen. Öffne Studio erneut über Semurai. Ungespeicherte Arbeit kann als HTML heruntergeladen werden.', duplicateSlide: 'Folie duplizieren', removeSlide: 'Folie löschen', moveUp: 'Nach vorne', moveDown: 'Nach hinten', back: 'Zurück zum Chat', saved: 'Gespeichert', unsaved: 'Ungespeicherte Änderungen', save: 'Speichern', preview: 'Vorschau', source: 'Quelltext', edit: 'Bearbeiten',
    desktop: 'Computer', tablet: 'Tablet', mobile: 'Mobil', undo: 'Rückgängig', redo: 'Wiederholen', history: 'Verlauf', export: 'Export',
    chat: 'Projektchat', ask: 'Was möchtest du am Projekt ändern?', send: 'Senden', working: 'Änderungen werden angewendet…', completed: 'Neue Version bereit',
    failed: 'Die Änderung konnte nicht abgeschlossen werden', cancelled: 'Abgebrochen', cancelling: 'Wird abgebrochen…', generatingImage: 'Bild wird generiert…', cancel: 'Abbrechen', retry: 'Erneut versuchen', restore: 'Wiederherstellen',
    empty: 'Dein Projekt beginnt mit einer Idee.', emptyHelp: 'Beschreibe, was du erstellen möchtest. Das Ergebnis erscheint hier.',
    error: 'Die Aktion konnte nicht abgeschlossen werden. Versuche es erneut.', conflict: 'Eine neuere Version wurde gespeichert. Lokale Änderungen bleiben im Editor.',
    notes: 'Sprechernotizen', present: 'Präsentieren', layers: 'Elemente', inspect: 'Stile und Eigenschaften', downloadHtml: 'HTML + CSS',
    downloadPptx: 'PowerPoint', print: 'Drucken / PDF', version: 'Version', loading: 'Projekt wird geöffnet…', close: 'Schließen',
    allChanges: 'Jede abgeschlossene KI-Änderung speichert eine neue Version.', localImage: 'Bild', zoom: 'Zoom', newProject: 'Semurai Creative',
    files: 'Projektdateien', html: 'index.html', css: 'CSS-Stile', fullscreen: 'Vollbild', savedSource: 'Projektquelltext',
    backToSemurai: 'Zurück zu Semurai', closeSession: 'Sitzung schließen', more: 'Weitere Optionen', collapsePanel: 'Bereich einklappen', expandPanel: 'Bereich einblenden',
    modeChat: 'Chat', modeEdit: 'Bearbeiten', tools: 'Werkzeuge', toolSelect: 'Auswählen', toolSelectHint: 'Projektvorschau und KI-Chat', toolComment: 'Kommentar', toolCommentHint: 'Projektelemente kommentieren',
    toolEdit: 'Bearbeiten', toolEditHint: 'Elemente manuell bearbeiten', openComments: 'Offene Kommentare', view: 'Ansicht', devices: 'Gerät',
    zoomIn: 'Vergrößern', zoomOut: 'Verkleinern', zoomFit: 'An Breite anpassen', presentStart: 'Von Anfang an', presentCurrent: 'Ab aktueller Folie', presenterView: 'Referentenansicht',
    sheet: 'Stylesheet', currentVersion: 'Aktuell', exportMenu: 'Exportoptionen' },
};

/** Copy for the docked Edit panel (StudioEditPanel and its field primitives). */
/** "<n> files" with the grammatical plural of each locale (Polish: plik / pliki / plików). */
export function studioFileCount(locale: keyof typeof studioEditorCopy, count: number): string {
  if (locale === 'pl') {
    const tens = count % 100, units = count % 10;
    return count + ' ' + (count === 1 ? 'plik' : units >= 2 && units <= 4 && (tens < 12 || tens > 14) ? 'pliki' : 'plików');
  }
  if (locale === 'de') return count + (count === 1 ? ' Datei' : ' Dateien');
  return count + (count === 1 ? ' file' : ' files');
}

export const studioEditPanelCopy = {
  pl: { title: 'Edycja', properties: 'Właściwości', modes: 'Tryb edycji', simple: 'Proste', pro: 'Pro', code: 'Kod', layers: 'Warstwy', layersEmpty: 'Warstwy pojawią się po wczytaniu podglądu.', expand: 'Rozwiń', collapse: 'Zwiń',
    parent: 'Zaznacz element nadrzędny', remove: 'Usuń element', deselect: 'Odznacz', path: 'Ścieżka elementu', page: 'Strona', pageHint: 'Kliknij element w podglądzie lub na liście warstw, aby go edytować. Zmiany widać od razu, a Zapisz tworzy nową wersję.',
    content: 'Treść', typography: 'Typografia', appearance: 'Wygląd', size: 'Wymiary', spacing: 'Odstępy', layout: 'Układ', style: 'Styl', border: 'Obramowanie',
    text: 'Tekst', textHint: 'Zatwierdź kliknięciem poza polem lub Ctrl+Enter.', href: 'Adres', src: 'Adres obrazu', alt: 'Opis', embedded: 'Obraz osadzony', changeImage: 'Zmień obraz', editHtml: 'Edytuj HTML w zakładce Kod',
    font: 'Krój', fontSize: 'Rozmiar', fontWeight: 'Grubość', lineHeight: 'Interlinia', letterSpacing: 'Odstęp liter', textAlign: 'Wyrównanie tekstu', color: 'Kolor', background: 'Tło', baseSize: 'Rozmiar bazowy',
    opacity: 'Krycie', radius: 'Promień', borderWidth: 'Grubość', borderStyle: 'Styl', width: 'Szerokość', height: 'Wysokość', padding: 'Wypełnienie', margin: 'Margines', link: 'Te same wartości ze wszystkich stron',
    all: 'Wszystkie', top: 'Góra', right: 'Prawo', bottom: 'Dół', left: 'Lewo', direction: 'Kierunek', justify: 'Rozłożenie', align: 'Wyrównanie', gap: 'Odstęp',
    alignLeft: 'Do lewej', alignCenter: 'Do środka', alignRight: 'Do prawej', alignJustify: 'Wyjustuj', row: 'Poziomo', column: 'Pionowo', rowReverse: 'Poziomo, odwrotnie', columnReverse: 'Pionowo, odwrotnie',
    start: 'Początek', center: 'Środek', end: 'Koniec', between: 'Równe odstępy', stretch: 'Rozciągnij', add: 'Dodaj:', addBorder: 'obramowanie', removeBorder: 'Usuń obramowanie',
    none: 'Brak', inherit: 'Domyślny', current: 'Obecny', pickColor: 'Wybierz kolor',
    invalidLength: 'Wpisz liczbę w px.', invalidLengthPercent: 'Wpisz liczbę w px lub %.', invalidLengthAuto: 'Wpisz liczbę w px albo auto.', invalidColor: 'Wpisz kolor w formacie #rrggbb.', invalidOpacity: 'Wpisz liczbę od 0 do 1.', invalidLineHeight: 'Wpisz liczbę albo wartość w px.', invalidOption: 'Wybierz wartość z listy.',
    html: 'HTML elementu', applyHtml: 'Zastosuj HTML', invalidHtml: 'Wpisz jeden poprawny element HTML.', htmlHint: 'Zmiana HTML dotyczy tylko zaznaczonego elementu.', htmlSelect: 'Zaznacz element, aby edytować jego HTML.' },
  en: { title: 'Edit', properties: 'Properties', modes: 'Edit mode', simple: 'Simple', pro: 'Pro', code: 'Code', layers: 'Layers', layersEmpty: 'Layers appear once the preview has loaded.', expand: 'Expand', collapse: 'Collapse',
    parent: 'Select parent element', remove: 'Delete element', deselect: 'Deselect', path: 'Element path', page: 'Page', pageHint: 'Click an element in the preview or in the layer list to edit it. Changes show up right away, and Save creates a new version.',
    content: 'Content', typography: 'Typography', appearance: 'Appearance', size: 'Sizing', spacing: 'Spacing', layout: 'Layout', style: 'Style', border: 'Border',
    text: 'Text', textHint: 'Click outside the field or press Ctrl+Enter to apply.', href: 'Link', src: 'Image URL', alt: 'Alt text', embedded: 'Embedded image', changeImage: 'Change image', editHtml: 'Edit HTML in the Code tab',
    font: 'Font', fontSize: 'Font size', fontWeight: 'Weight', lineHeight: 'Line height', letterSpacing: 'Letter spacing', textAlign: 'Text alignment', color: 'Color', background: 'Background', baseSize: 'Base size',
    opacity: 'Opacity', radius: 'Radius', borderWidth: 'Width', borderStyle: 'Style', width: 'Width', height: 'Height', padding: 'Padding', margin: 'Margin', link: 'Same value on all sides',
    all: 'All', top: 'Top', right: 'Right', bottom: 'Bottom', left: 'Left', direction: 'Direction', justify: 'Justify', align: 'Align', gap: 'Gap',
    alignLeft: 'Left', alignCenter: 'Center', alignRight: 'Right', alignJustify: 'Justify', row: 'Horizontal', column: 'Vertical', rowReverse: 'Horizontal, reversed', columnReverse: 'Vertical, reversed',
    start: 'Start', center: 'Center', end: 'End', between: 'Space between', stretch: 'Stretch', add: 'Add:', addBorder: 'border', removeBorder: 'Remove border',
    none: 'None', inherit: 'Default', current: 'Current', pickColor: 'Pick a color',
    invalidLength: 'Enter a number in px.', invalidLengthPercent: 'Enter a number in px or %.', invalidLengthAuto: 'Enter a number in px or auto.', invalidColor: 'Enter a color as #rrggbb.', invalidOpacity: 'Enter a number from 0 to 1.', invalidLineHeight: 'Enter a number or a px value.', invalidOption: 'Pick a value from the list.',
    html: 'Element HTML', applyHtml: 'Apply HTML', invalidHtml: 'Enter one valid HTML element.', htmlHint: 'HTML changes affect only the selected element.', htmlSelect: 'Select an element to edit its HTML.' },
  de: { title: 'Bearbeiten', properties: 'Eigenschaften', modes: 'Bearbeitungsmodus', simple: 'Einfach', pro: 'Pro', code: 'Code', layers: 'Ebenen', layersEmpty: 'Ebenen erscheinen, sobald die Vorschau geladen ist.', expand: 'Aufklappen', collapse: 'Zuklappen',
    parent: 'Übergeordnetes Element auswählen', remove: 'Element löschen', deselect: 'Auswahl aufheben', path: 'Elementpfad', page: 'Seite', pageHint: 'Klicke auf ein Element in der Vorschau oder in der Ebenenliste, um es zu bearbeiten. Änderungen sind sofort sichtbar, Speichern erstellt eine neue Version.',
    content: 'Inhalt', typography: 'Typografie', appearance: 'Darstellung', size: 'Abmessungen', spacing: 'Abstände', layout: 'Anordnung', style: 'Stil', border: 'Rahmen',
    text: 'Text', textHint: 'Zum Übernehmen außerhalb klicken oder Strg+Enter drücken.', href: 'Link', src: 'Bild-URL', alt: 'Alternativtext', embedded: 'Eingebettetes Bild', changeImage: 'Bild ändern', editHtml: 'HTML im Tab Code bearbeiten',
    font: 'Schrift', fontSize: 'Größe', fontWeight: 'Stärke', lineHeight: 'Zeilenhöhe', letterSpacing: 'Laufweite', textAlign: 'Textausrichtung', color: 'Farbe', background: 'Hintergrund', baseSize: 'Grundgröße',
    opacity: 'Deckkraft', radius: 'Radius', borderWidth: 'Stärke', borderStyle: 'Stil', width: 'Breite', height: 'Höhe', padding: 'Innenabstand', margin: 'Außenabstand', link: 'Gleicher Wert auf allen Seiten',
    all: 'Alle', top: 'Oben', right: 'Rechts', bottom: 'Unten', left: 'Links', direction: 'Richtung', justify: 'Verteilung', align: 'Ausrichtung', gap: 'Abstand',
    alignLeft: 'Links', alignCenter: 'Zentriert', alignRight: 'Rechts', alignJustify: 'Blocksatz', row: 'Horizontal', column: 'Vertikal', rowReverse: 'Horizontal, umgekehrt', columnReverse: 'Vertikal, umgekehrt',
    start: 'Anfang', center: 'Mitte', end: 'Ende', between: 'Gleichmäßig verteilt', stretch: 'Strecken', add: 'Hinzufügen:', addBorder: 'Rahmen', removeBorder: 'Rahmen entfernen',
    none: 'Keine', inherit: 'Standard', current: 'Aktuell', pickColor: 'Farbe wählen',
    invalidLength: 'Gib eine Zahl in px ein.', invalidLengthPercent: 'Gib eine Zahl in px oder % ein.', invalidLengthAuto: 'Gib eine Zahl in px oder auto ein.', invalidColor: 'Gib eine Farbe als #rrggbb ein.', invalidOpacity: 'Gib eine Zahl von 0 bis 1 ein.', invalidLineHeight: 'Gib eine Zahl oder einen px-Wert ein.', invalidOption: 'Wähle einen Wert aus der Liste.',
    html: 'Element-HTML', applyHtml: 'HTML anwenden', invalidHtml: 'Gib ein gültiges HTML-Element ein.', htmlHint: 'HTML-Änderungen betreffen nur das ausgewählte Element.', htmlSelect: 'Wähle ein Element aus, um sein HTML zu bearbeiten.' },
};
export type StudioEditPanelCopy = typeof studioEditPanelCopy.pl;
