export const studioEditorCopy = {
  pl: { exportHistory: 'Zapisane eksporty', noExports: 'Wyeksportowane pliki pojawią się tutaj.', downloadAgain: 'Pobierz ponownie', exportSaveFailed: 'Plik został pobrany, ale nie udało się zapisać jego kopii w projekcie.', expired: 'Sesja wygasła. Otwórz Studio ponownie z Semurai. Niezapisany projekt możesz pobrać jako HTML.', duplicateSlide: 'Duplikuj slajd', removeSlide: 'Usuń slajd', moveUp: 'Przesuń wcześniej', moveDown: 'Przesuń dalej', back: 'Wróć do czatu', saved: 'Zapisano', unsaved: 'Niezapisane zmiany', save: 'Zapisz', preview: 'Podgląd', source: 'Źródło', edit: 'Edytuj',
    desktop: 'Komputer', tablet: 'Tablet', mobile: 'Telefon', undo: 'Cofnij', redo: 'Ponów', history: 'Historia', export: 'Eksport',
    chat: 'Czat projektu', ask: 'Co chcesz zmienić w projekcie?', send: 'Wyślij', working: 'Wprowadzam zmiany…', completed: 'Nowa wersja gotowa',
    failed: 'Nie udało się ukończyć zmiany', cancelled: 'Anulowano', cancel: 'Anuluj', retry: 'Spróbuj ponownie', restore: 'Przywróć',
    empty: 'Twój projekt czeka na pierwszy pomysł.', emptyHelp: 'Opisz, co chcesz stworzyć. Wynik pojawi się tutaj.',
    error: 'Nie udało się wykonać tej operacji. Spróbuj ponownie.', conflict: 'Zapisano nowszą wersję. Twoje lokalne zmiany pozostają w edytorze.',
    notes: 'Notatki prelegenta', present: 'Prezentuj', layers: 'Elementy', inspect: 'Style i właściwości', downloadHtml: 'HTML + CSS',
    downloadPptx: 'PowerPoint', print: 'Drukuj / PDF', version: 'Wersja', loading: 'Otwieram projekt…', close: 'Zamknij',
    allChanges: 'Każda ukończona zmiana AI zapisuje nową wersję.', localImage: 'Obraz', zoom: 'Powiększenie', newProject: 'Semurai Creative',
    files: 'Pliki projektu', html: 'index.html', css: 'Style CSS', fullscreen: 'Pełny ekran', savedSource: 'Źródło projektu' },
  en: { exportHistory: 'Saved exports', noExports: 'Your exported files will appear here.', downloadAgain: 'Download again', exportSaveFailed: 'Your file was downloaded, but a copy could not be saved to this project.', expired: 'Session expired. Reopen Studio from Semurai. You can download unsaved work as HTML.', duplicateSlide: 'Duplicate slide', removeSlide: 'Delete slide', moveUp: 'Move earlier', moveDown: 'Move later', back: 'Back to chat', saved: 'Saved', unsaved: 'Unsaved changes', save: 'Save', preview: 'Preview', source: 'Source', edit: 'Edit',
    desktop: 'Desktop', tablet: 'Tablet', mobile: 'Mobile', undo: 'Undo', redo: 'Redo', history: 'History', export: 'Export',
    chat: 'Project chat', ask: 'What would you like to change?', send: 'Send', working: 'Applying changes…', completed: 'New version ready',
    failed: 'The change could not be completed', cancelled: 'Cancelled', cancel: 'Cancel', retry: 'Retry', restore: 'Restore',
    empty: 'Your project starts with an idea.', emptyHelp: 'Describe what you want to create. Your result will appear here.',
    error: 'This action could not be completed. Please try again.', conflict: 'A newer version was saved. Your local changes remain in the editor.',
    notes: 'Speaker notes', present: 'Present', layers: 'Elements', inspect: 'Styles and properties', downloadHtml: 'HTML + CSS',
    downloadPptx: 'PowerPoint', print: 'Print / PDF', version: 'Version', loading: 'Opening project…', close: 'Close',
    allChanges: 'Each completed AI change saves a new version.', localImage: 'Image', zoom: 'Zoom', newProject: 'Semurai Creative',
    files: 'Project files', html: 'index.html', css: 'CSS styles', fullscreen: 'Full screen', savedSource: 'Project source' },
  de: { exportHistory: 'Gespeicherte Exporte', noExports: 'Exportierte Dateien erscheinen hier.', downloadAgain: 'Erneut herunterladen', exportSaveFailed: 'Die Datei wurde heruntergeladen, aber eine Kopie konnte nicht im Projekt gespeichert werden.', expired: 'Sitzung abgelaufen. Öffne Studio erneut über Semurai. Ungespeicherte Arbeit kann als HTML heruntergeladen werden.', duplicateSlide: 'Folie duplizieren', removeSlide: 'Folie löschen', moveUp: 'Nach vorne', moveDown: 'Nach hinten', back: 'Zurück zum Chat', saved: 'Gespeichert', unsaved: 'Ungespeicherte Änderungen', save: 'Speichern', preview: 'Vorschau', source: 'Quelltext', edit: 'Bearbeiten',
    desktop: 'Computer', tablet: 'Tablet', mobile: 'Mobil', undo: 'Rückgängig', redo: 'Wiederholen', history: 'Verlauf', export: 'Export',
    chat: 'Projektchat', ask: 'Was möchtest du am Projekt ändern?', send: 'Senden', working: 'Änderungen werden angewendet…', completed: 'Neue Version bereit',
    failed: 'Die Änderung konnte nicht abgeschlossen werden', cancelled: 'Abgebrochen', cancel: 'Abbrechen', retry: 'Erneut versuchen', restore: 'Wiederherstellen',
    empty: 'Dein Projekt beginnt mit einer Idee.', emptyHelp: 'Beschreibe, was du erstellen möchtest. Das Ergebnis erscheint hier.',
    error: 'Die Aktion konnte nicht abgeschlossen werden. Versuche es erneut.', conflict: 'Eine neuere Version wurde gespeichert. Lokale Änderungen bleiben im Editor.',
    notes: 'Sprechernotizen', present: 'Präsentieren', layers: 'Elemente', inspect: 'Stile und Eigenschaften', downloadHtml: 'HTML + CSS',
    downloadPptx: 'PowerPoint', print: 'Drucken / PDF', version: 'Version', loading: 'Projekt wird geöffnet…', close: 'Schließen',
    allChanges: 'Jede abgeschlossene KI-Änderung speichert eine neue Version.', localImage: 'Bild', zoom: 'Zoom', newProject: 'Semurai Creative',
    files: 'Projektdateien', html: 'index.html', css: 'CSS-Stile', fullscreen: 'Vollbild', savedSource: 'Projektquelltext' },
};
